version: "3.7"
services:
  api:
    restart: on-failure
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    depends_on:
      - lukecossey-db
    env_file:
      - ./api/.env
    ports:
      - "9000:9000"
      - "9001:9001"
    links:
      - lukecossey-db
  client:
    restart: on-failure
    build:
      context: .
      dockerfile: docker/client/Dockerfile
    env_file:
      - ./client/.env
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules/
    links:
      - api
  lukecossey-db:
    image: mongo
    ports:
      - "27017:27017"
